#----------------------------------------------------------------------------
#  Copyright (c) 2020 WSO2, Inc. http://www.wso2.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#----------------------------------------------------------------------------

# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrantfile to locally test the ansible playbook changes

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.hostname = "azure-wso2ei"
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.vm.synced_folder "ansible-apim/", "/home/vagrant/ansible-apim"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "wso2-oracle"
  end
  #config.vm.provision :shell, path: "./scripts/init.sh"
  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible-ei/site.yml"
  #  ansible.inventory_path = "ansible-ei/dev"
  #  ansible.limit = 'all'
  #end
end
